export const REGISTER_AUTH_REQUEST = "REGISTER_AUTH_REQUEST";
export const REGISTER_AUTH_SUCCESS = "REGISTER_AUTH_SUCCESS";
export const REGISTER_AUTH_ERROR = "REGISTER_AUTH_ERROR";
export const LOGIN_AUTH_REQUEST = "LOGIN_AUTH_REQUEST";
export const LOGIN_AUTH_ERROR = "LOGIN_AUTH_ERROR";
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";
export const LOGOUT_AUTH_REQUEST = "LOGOUT_AUTH_REQUEST";
export const LOGOUT_AUTH_SUCCESS = "LOGOUT_AUTH_SUCCESS";
